easy_admin:
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash'}
            - { name: 'new', icon: 'plus', label: 'Nouveau'}
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Entreprise:
            class: App\Entity\Entreprise
            label: 'Gestion des entreprises'
            list:
                fields:
                    - id
                    - nom
                    - adresse
                    - { property: 'activite', label: "Activité" }
                    - { property: 'stages', label: "Nb stages" }
            new:
                title: 'Ajouter une entreprise'
            eidt:
                title: 'Éditer une entreprise'
        Stage:
            class: App\Entity\Stage
            label: 'Gestion des stages'
            list:
                fields:
                    - id
                    - titre
                    - { property: 'mailContact', label: 'Mail', type: 'email'}
                    - { property: 'dateDebut', label: 'Date début' }
                    - dateFin
                    - entreprise
            form:
                fields:
                    - { type: 'group', label: 'Le stage', icon: 'laptop' }
                    - titre
                    - description
                    - formations
                    - { property: 'dateDebut', type_options: { widget: 'single_text' } }
                    - { property: 'dateFin', type_options: { widget: 'single_text' } }
                    - { type: 'group', label: "Informations concernant l'entreprise", icon: 'suitcase' }
                    - entreprise
                    - mailContact
            new:
                title:  'Ajouter un stage'
            edit:
                title:  'Éditer un stage'
        Formation:
            class: App\Entity\Formation
            label: 'Gestion des formations'
            list:
                fields:
                    - nom
                    - { property: stages, label: "Nb stages" }
            form:
                fields:
                    - nom
            new:
                title: 'Ajouter une formation'
            eidt:
                title: 'Éditer une formation'                



                    
    site_name: <img src="https://i.ytimg.com/vi/_N4XunFaSnU/mqdefault.jpg" /><center>Les stages de Nounours</center>
    design:
        brand_color: '#a36b00'