security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    toufik: { password:  $2y$15$Fv.krU0ryNNOpTNRCdI7HeKwUU/0Kq3PpjrTAtstFO84nqcCfpKNu,roles: ROLE_ADMIN}
                    cedrik: { password:  $2y$15$Fv.krU0ryNNOpTNRCdI7HeKwUU/0Kq3PpjrTAtstFO84nqcCfpKNu,roles: ROLE_USER}
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            http_basic: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/ajoutEntreprise, roles: ROLE_ADMIN }
        - { path: ^/modificationEntreprise, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: [ROLE_ADMIN, ROLE_USER] }
    
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      15
